### ISSUE TITLE
Canvas: Open "Query" prompt when user clicks on (+)

### ISSUE THREAD

**Issue by smurff** [CentrifugeTech/BlueWave#11]
Current behavior is the user must drag and drop a query out of the menu tab.

To speed interaction up, when user clicks on  simply open a Query prompt

Please align the Query prompt on the page, centered under "Explore Data".  Ideally top of Query window is close to be aligned with the top of the menu bar.

<img width="1612" alt="Screen Shot 2021-04-13 at 11 50 33 AM" src="https://user-images.githubusercontent.com/1130590/114791116-c3964000-9d3a-11eb-94d2-d9d73a543401.png">

**Comment by pborissow** [comment]
Plus icon was replaced a long time ago

**Comment by pborissow** [comment]
The icons must be dragged onto the canvas. I added a prompt/hint for users

![image](https://user-images.githubusercontent.com/10224874/144126443-5ee49a7d-7cdc-422a-bba2-3fca3a616cc4.png)
