### ISSUE TITLE
Canvas: Replace "+" Icon with Cloud Icon

### ISSUE THREAD

**Issue by smurff** [CentrifugeTech/BlueWave#12]
Instead of the “+” icon, let’s use cloud icon designed for the project

![Cloudy White Balance](https://user-images.githubusercontent.com/1130590/114791205-f8a29280-9d3a-11eb-9a9e-82485c8c6bbe.png)

**Comment by pborissow** [comment]
Icon was replaced with a database icon instead of cloud
