### ISSUE TITLE
Add Title to ChartEditor

### ISSUE THREAD

**Issue by pborissow** [CentrifugeTech/BlueWave#3]
We should have a title that appears above the chart in the ChartEditor. Initially, it will be "Untitled". The user can update the title by clicking on the title area. The title should be stored in the chart config.

**Comment by smurff** [comment]
<img width="1413" alt="Screen Shot 2021-04-13 at 4 32 25 PM" src="https://user-images.githubusercontent.com/1130590/114788638-b24b3480-9d36-11eb-9de1-a20b66e78cb8.png">

**Comment by pborissow** [comment]
Fixed in feat/3
