### ISSUE TITLE
Sankey Enhancements

### ISSUE THREAD

**Issue by pborissow** [CentrifugeTech/BlueWave#45]
- Provide hints when tree is out of balance
- Ensure support of multiple distributors
- Allow users to set/update title
- Ensure node names are unique

**Comment by smurff** [comment]
To make the Sankey useful, we will want the ability to show values within the distribution points.  At first, they should be manual.
<img width="1674" alt="Screen Shot 2021-05-20 at 5 17 11 PM" src="https://user-images.githubusercontent.com/1130590/119066292-4e9ad380-b994-11eb-809f-c64c5a49f27a.png">
.

- Eventually, we want the ability to allow for a user to assign an API endpoint.
- We likely may want to also allow for "Add value", which creates a new field + value pair.

<img width="831" alt="Screen Shot 2021-05-20 at 5 45 16 PM" src="https://user-images.githubusercontent.com/1130590/119066320-61150d00-b994-11eb-8ebb-80394e2d1eff.png">
