### ISSUE TITLE
Other menu selection buttons are not reacting or available 

### ISSUE THREAD

**Issue by smurff** [CentrifugeTech/BlueWave#47]
User is unable to select other options after setting up the database query.

<img width="1611" alt="Screen Shot 2021-05-11 at 1 49 45 PM" src="https://user-images.githubusercontent.com/1130590/117883271-11319a00-b260-11eb-9d36-5bd3793b2924.png">

**Comment by pborissow** [comment]
Fixed in last commit on feat/28
