### ISSUE TITLE
Create Runnable jar file from build

### ISSUE THREAD

**Issue by lmohseni-smc** [CentrifugeTech/BlueWave#86]
Steps to reproduce:
1.  mvn clean package
2.  java -jar target/bluewave-1.0.0.jar -config ../config.json

Result:
`Exception in thread "main" java.lang.NoClassDefFoundError`

Expected result:
jar file is able to successfully be invoked via `java -jar`

**Comment by pborissow** [comment]
This is a non-issue. All of the developers and testers have been able to create a runnable jar using a standard IDE from day one.
