### ISSUE TITLE
CPU utilization 

### ISSUE THREAD

**Issue by swordysrepo** [CentrifugeTech/BlueWave#96]
When the app is running the CPU usage gradually gets higher, after a long time (a few hours to a day) the CPU is nearly maxed out by the Java runtime. Suggesting there is a memory/cache "leak", and currently the app initialization would need to be reset manually or this caching reduced/dumped. I haven't seen whether the increased CPU use is directly related to the app getting refreshed during use, or whether this reflects the duration of time the app is running. My version of the app is refreshed 100+ times before this becomes an issue and usually is open 5+ hours before getting a reset.
[task manager](https://imgur.com/a/LxWIwsD)

these two articles suggest that this is a garbage collection issue
https://tech.asimio.net/2016/02/11/Troubleshoot-high-CPU-usage-in-Java-applications.html
https://stackoverflow.com/questions/15811411/high-cpu-utilization-in-java-application-why

**Comment by swordysrepo** [comment]
I see we could force garbage collection with call to `System.gc()`

**Comment by pborissow** [comment]
This issue seems to affect windows users using java 11 or higher. The issue is deep inside the javaxt-server library, somewhere in the jetty code.
